import os
import re

# ملفات بمحتوى مبدئي
DEFAULT_FILE_CONTENT = {
    "main.py": 'print("Hello from hel-diagram")\n',
    "README.md": '# Project Title\n\nThis project was generated by hel-diagram.\n',
}

def build_tree_from_file(diagram_path, output_dir):
    with open(diagram_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    if not lines:
        return

    # الجذر
    for line in lines:
        match = re.match(r'^[\s│]*[📁📄]?\s*(.+?)/\s*$', line.strip())
        if match:
            root_name = match.group(1).strip()
            break
    else:
        return

    base_dir = os.path.join(output_dir, root_name)
    os.makedirs(base_dir, exist_ok=True)
    path_stack = [base_dir]

    for line in lines[1:]:
        if not line.strip():
            continue

        # العمق
        indent_part = re.match(r'^([ \t│]*)', line).group(1)
        # احتساب العمق بدقة
        depth = indent_part.count("│") + indent_part.count("    ")

        # تنظيف الرموز
        content = re.sub(r'^[\s│]*[├└]──\s*', '', line.strip())
        content = re.sub(r'^[📁📄]\s*', '', content).strip()
        if not content:
            continue

        while len(path_stack) > depth + 1:
            path_stack.pop()

        current_path = os.path.join(path_stack[-1], content)

        if '.' in content:
            # تأكد أن مجلد الأب موجود
            os.makedirs(os.path.dirname(current_path), exist_ok=True)
            with open(current_path, "w", encoding="utf-8") as f:
                f.write(DEFAULT_FILE_CONTENT.get(content, ""))
        else:
            os.makedirs(current_path, exist_ok=True)
            path_stack.append(current_path)
